# Generated by Django 3.2.9 on 2021-12-04 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateField(auto_created=True, verbose_name='Ngày tạo')),
                ('name', models.CharField(default='', max_length=255, verbose_name='Tên danh mục')),
                ('slug', models.SlugField(blank=True, max_length=500, unique=True, verbose_name='URL')),
                ('update_at', models.DateField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('status', models.BooleanField(default=True, verbose_name='Trạng thái')),
            ],
            options={
                'verbose_name': 'Danh mục sản phẩm',
                'verbose_name_plural': 'Danh mục sản phẩm',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_created=True, verbose_name='Ngày tạo')),
                ('name', models.CharField(default='', max_length=255, verbose_name='Tên sản phẩm')),
                ('unique_product', models.CharField(blank=True, max_length=20, unique=True, verbose_name='UID sản phẩm')),
                ('cover_image', models.ImageField(blank=True, max_length=512, upload_to='media/upload/products/2021/12', verbose_name='Image')),
                ('slug', models.SlugField(blank=True, max_length=500, unique=True, verbose_name='URL')),
                ('price', models.FloatField(default=0, verbose_name='Giá')),
                ('quantity', models.IntegerField(default=0, verbose_name='Số lượng')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('status', models.BooleanField(default=True, verbose_name='Trạng thái')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='quote.category')),
            ],
            options={
                'verbose_name': 'Sản Phẩm',
                'verbose_name_plural': 'Sản Phẩm',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, verbose_name='Tên dung tích')),
                ('unique_volume', models.CharField(blank=True, max_length=20, unique=True, verbose_name='UID Dung tích')),
                ('status', models.BooleanField(default=True, verbose_name='Trạng thái')),
                ('create_at', models.DateField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('update_at', models.DateField(auto_now=True, verbose_name='Cập nhật')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volume_product', to='quote.product')),
            ],
            options={
                'verbose_name': 'Dung tích sản phẩm',
                'verbose_name_plural': 'Dung tích sản phẩm',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Stamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, verbose_name='Tên tem nhãn')),
                ('type_stamp', models.CharField(default='', max_length=255, verbose_name='Loại tem nhãn')),
                ('price', models.FloatField(default=0, verbose_name='Giá')),
                ('note', models.TextField(default='', verbose_name='Ghi chú')),
                ('create_at', models.DateField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('update_at', models.DateField(auto_now=True, verbose_name='Cập nhật')),
                ('status', models.BooleanField(default=True, verbose_name='Trạng thái')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stamp_product', to='quote.product', verbose_name='Sản phẩm')),
                ('volume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stamp_volume', to='quote.volume', verbose_name='Dung tích')),
            ],
            options={
                'verbose_name': 'Tem nhãn',
                'verbose_name_plural': 'Tem nhãn',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PackingWorker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, verbose_name='Tên gói chi phí công nhân đóng gói')),
                ('price', models.FloatField(default=0, verbose_name='Giá')),
                ('note', models.TextField(default='', verbose_name='Ghi chú')),
                ('create_at', models.DateField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('update_at', models.DateField(auto_now=True, verbose_name='Cập nhật')),
                ('status', models.BooleanField(default=True, verbose_name='Trạng thái')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packing_worker_product', to='quote.product', verbose_name='Sản phẩm')),
                ('volume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packing_worker_volume', to='quote.volume', verbose_name='Dung tích')),
            ],
            options={
                'verbose_name': 'Nhân công đóng gói',
                'verbose_name_plural': 'Nhân công đóng gói',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PackagingLevel2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, verbose_name='Tên bao bì cấp 2')),
                ('price', models.FloatField(default=0, verbose_name='Giá bao bì')),
                ('type_packaging', models.CharField(default='', max_length=50, verbose_name='Loại bao bì')),
                ('note', models.TextField(default='', verbose_name='Ghi chú')),
                ('status', models.BooleanField(default=True, verbose_name='Trạng thái')),
                ('create_at', models.DateField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('update_at', models.DateField(auto_now=True, verbose_name='Cập nhật')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packaging_product', to='quote.product', verbose_name='Sản phẩm')),
                ('volume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packaging_volume', to='quote.volume', verbose_name='Dung tích')),
            ],
            options={
                'verbose_name': 'Bao bì cấp 2',
                'verbose_name_plural': 'Bao bì cấp 2',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PackagingLevel1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, verbose_name='Tên bao bì cấp 1')),
                ('type_packaging', models.CharField(default='', max_length=50, verbose_name='Loại bao bì')),
                ('image', models.ImageField(blank=True, max_length=512, upload_to='media/upload/images/2021/12', verbose_name='Image')),
                ('type_material', models.CharField(default='', max_length=255, verbose_name='Chất liệu')),
                ('quantity_provider_sell', models.IntegerField(default=0, verbose_name='Chất liệu NCC có thể bán')),
                ('min_order', models.IntegerField(default=0, verbose_name='Min order')),
                ('provider', models.CharField(default='', max_length=255, verbose_name='Nhà cung cấp')),
                ('price', models.FloatField(default=0, verbose_name='Giá')),
                ('quantity_can_order_with_price', models.IntegerField(default=0, verbose_name='Số lượng đặt hàng tương ứng với giá')),
                ('time_to_send', models.TextField(default='', verbose_name='Thời gian giao hàng')),
                ('note', models.TextField(default='', verbose_name='Ghi chú')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('status', models.BooleanField(default=True, verbose_name='Trạng thái')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packaging_level_1_product', to='quote.product')),
                ('volume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packagin_level1_volume', to='quote.volume', verbose_name='Dung tích')),
            ],
            options={
                'verbose_name': 'Bao bì cấp 1',
                'verbose_name_plural': 'Bao bì cấp 1',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, verbose_name='Tên nguyên liệu')),
                ('price', models.FloatField(default=0, verbose_name='Giá nguyên liệu')),
                ('status', models.BooleanField(default=True, verbose_name='Trạng thái')),
                ('note', models.TextField(blank=True, default='', null=True, verbose_name='Ghi chú')),
                ('create_at', models.DateField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('update_at', models.DateField(auto_now=True, verbose_name='Cập nhật')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_product', to='quote.product', verbose_name='Sản phẩm')),
                ('volume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_volume', to='quote.volume', verbose_name='Dung tích')),
            ],
            options={
                'verbose_name': 'Nguyên liệu',
                'verbose_name_plural': 'Nguyên liệu',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FeeShipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, verbose_name='Tên gói phí vận chuyển')),
                ('price', models.FloatField(default=0, verbose_name='Giá')),
                ('note', models.TextField(default='', verbose_name='Ghi chú')),
                ('create_at', models.DateField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('update_at', models.DateField(auto_now=True, verbose_name='Cập nhật')),
                ('status', models.BooleanField(default=True, verbose_name='Trạng thái')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_shipping_product', to='quote.product', verbose_name='Sản phẩm')),
                ('volume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_shipping_volume', to='quote.volume', verbose_name='Dung tích')),
            ],
            options={
                'verbose_name': 'Vận chuyển',
                'verbose_name_plural': 'Vận chuyển',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Announced',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, verbose_name='Tên gói công bố kiểm nghiệm')),
                ('price', models.FloatField(default=0, verbose_name='Giá')),
                ('note', models.TextField(default='', verbose_name='Ghi chú')),
                ('create_at', models.DateField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('update_at', models.DateField(auto_now=True, verbose_name='Cập nhật')),
                ('status', models.BooleanField(default=True, verbose_name='Trạng thái')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annonced_product', to='quote.product', verbose_name='Sản phẩm')),
                ('volume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annonced_volume', to='quote.volume', verbose_name='Dung tích')),
            ],
            options={
                'verbose_name': 'Công bố kiểm nghiệm',
                'verbose_name_plural': 'Công bố kiểm nghiệm',
                'ordering': ['name'],
            },
        ),
    ]
