# Generated by Django 3.2.9 on 2021-12-17 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0003_material_cover_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Param',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(blank=True, verbose_name='URL')),
                ('md5', models.CharField(blank=True, default='', max_length=255, verbose_name='MD5')),
            ],
            options={
                'verbose_name': 'Bảng url export PDF',
                'verbose_name_plural': 'Bảng export PDF',
                'ordering': ['id'],
            },
        ),
    ]
