# Generated by Django 3.2.9 on 2021-12-20 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0004_param'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volume',
            name='product',
        ),
    ]
