# Generated by Django 4.0 on 2021-12-24 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0007_auto_20211222_1711'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerHome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_created=True, verbose_name='Ngày tạo')),
                ('image', models.ImageField(blank=True, max_length=512, upload_to='media/upload/bannerhome/2021/12', verbose_name='Image')),
                ('status', models.BooleanField(default=True, verbose_name='Trạng thái')),
            ],
            options={
                'verbose_name': 'Banner trang chủ',
                'verbose_name_plural': 'Banner trang chủ',
                'ordering': ['id'],
            },
        ),
    ]
