# Generated by Django 3.2.8 on 2021-12-10 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0008_material_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='des',
            field=models.TextField(blank=True, default='', verbose_name='Mô tả'),
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0, verbose_name='lượt tạo báo giá')),
                ('creat_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('update_at', models.DateField(auto_now=True, verbose_name='Cập nhật')),
                ('status', models.BooleanField(default=True, verbose_name='Trạng thái')),
                ('announced', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_announced', to='quote.announced', verbose_name='Gói công bố kiểm nghiệm')),
                ('feeship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_feeship', to='quote.feeshipping', verbose_name='Gói vận chuyển')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_material', to='quote.material', verbose_name='Nguyên liệu')),
                ('packaging_level1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_packaging_level1', to='quote.packaginglevel1', verbose_name='Bao bì cấp 1')),
                ('packaging_level2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_packaging_level2', to='quote.packaginglevel2', verbose_name='Bao bì cấp 2')),
                ('packing_worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_packingworker', to='quote.packingworker', verbose_name='Gói nhân công đóng gói')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_product', to='quote.product', verbose_name='Sản phẩm')),
                ('stamp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_stamp', to='quote.stamp', verbose_name='Gói tem nhãn')),
                ('volume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_volume', to='quote.volume', verbose_name='Dung tích')),
            ],
            options={
                'verbose_name': 'Bảng báo giá',
                'verbose_name_plural': 'Bảng báo giá',
                'ordering': ['id'],
            },
        ),
    ]
