# Generated by Django 4.0 on 2021-12-28 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0009_remove_feeshipping_product_remove_feeshipping_volume_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=512, upload_to='media/upload/logo/2021/12', verbose_name='Logo')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
            ],
            options={
                'verbose_name': 'Logo',
                'verbose_name_plural': 'Logo',
                'ordering': ['id'],
            },
        ),
        migrations.RemoveField(
            model_name='announced',
            name='product',
        ),
        migrations.RemoveField(
            model_name='announced',
            name='volume',
        ),
        migrations.RemoveField(
            model_name='material',
            name='volume',
        ),
        migrations.RemoveField(
            model_name='packaginglevel2',
            name='product',
        ),
        migrations.AddField(
            model_name='packaginglevel2',
            name='product',
            field=models.ManyToManyField(blank=True, to='quote.Product', verbose_name='Sản phẩm'),
        ),
    ]
