# Generated by Django 3.2.8 on 2021-12-13 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0009_auto_20211210_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='cover_image',
            field=models.ImageField(blank=True, max_length=512, upload_to='media/upload/material/2021/12', verbose_name='Image'),
        ),
    ]
