# Generated by Django 3.2.8 on 2022-01-05 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0010_logo_remove_announced_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='packaginglevel2',
            name='quantity_can_order_with_price',
            field=models.IntegerField(default=0, verbose_name='Số lượng đặt hàng tương ứng với giá'),
        ),
        migrations.AlterField(
            model_name='bannerhome',
            name='image',
            field=models.ImageField(blank=True, max_length=512, upload_to='media/upload/bannerhome/2022/1', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='imagematerial',
            name='image',
            field=models.ImageField(blank=True, max_length=512, upload_to='media/upload/materials/2022/1', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='imagepackaginglevel1',
            name='image',
            field=models.ImageField(blank=True, max_length=512, upload_to='media/upload/packaginglevel1/2022/1', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='imagepackaginglevel2',
            name='image',
            field=models.ImageField(blank=True, max_length=512, upload_to='media/upload/packaginglevel1/2022/1', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='imageproduct',
            name='image',
            field=models.ImageField(blank=True, max_length=512, upload_to='media/upload/products/2022/1', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='logo',
            name='image',
            field=models.ImageField(max_length=512, upload_to='media/upload/logo/2022/1', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='material',
            name='cover_image',
            field=models.ImageField(blank=True, max_length=512, upload_to='media/upload/material/2022/1', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='packaginglevel1',
            name='image',
            field=models.ImageField(blank=True, max_length=512, upload_to='media/upload/images/2022/1', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='packaginglevel2',
            name='image',
            field=models.ImageField(blank=True, max_length=512, upload_to='media/upload/images/2022/1', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cover_image',
            field=models.ImageField(blank=True, max_length=512, upload_to='media/upload/products/2022/1', verbose_name='Image'),
        ),
    ]
