# Generated by Django 3.2.8 on 2021-12-20 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0011_param'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volume',
            name='product',
        ),
    ]
