# Generated by Django 3.2.8 on 2022-01-13 03:32

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0011_auto_20220105_1716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='for_create_quote',
        ),
        migrations.AddField(
            model_name='material',
            name='note_material',
            field=models.TextField(blank=True, default='', verbose_name='Ghi chú'),
        ),
        migrations.AlterField(
            model_name='material',
            name='note',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Mô tả'),
        ),
    ]
