# Generated by Django 3.2.8 on 2022-01-13 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0013_material_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='packaginglevel1',
            name='slug',
            field=models.SlugField(blank=True, max_length=500, null=True, unique=True, verbose_name='URL'),
        ),
    ]
