# Generated by Django 3.2.8 on 2021-12-21 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0013_imageproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, max_length=512, upload_to='media/upload/materials/2021/12', verbose_name='Image')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_media', to='quote.material', verbose_name='Material')),
            ],
            options={
                'verbose_name': 'Hình ảnh Nguyên liệu',
                'verbose_name_plural': 'Hình ảnh Nguyên liệu',
                'ordering': ['id'],
            },
        ),
    ]
