# Generated by Django 3.2.8 on 2021-12-21 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0014_imagematerial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagePackagingLevel1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, max_length=512, upload_to='media/upload/packaginglevel1/2021/12', verbose_name='Image')),
                ('packaginglevel1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_media', to='quote.packaginglevel1', verbose_name='PackagingLevel1')),
            ],
            options={
                'verbose_name': 'Hình ảnh Bao bì cấp 1',
                'verbose_name_plural': 'Hình ảnh Bao bì cấp 1',
                'ordering': ['id'],
            },
        ),
    ]
