# Generated by Django 3.2.8 on 2021-12-22 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0015_imagepackaginglevel1'),
    ]

    operations = [
        migrations.AddField(
            model_name='packaginglevel2',
            name='image',
            field=models.ImageField(blank=True, max_length=512, upload_to='media/upload/images/2021/12', verbose_name='Image'),
        ),
        migrations.CreateModel(
            name='ImagePackagingLevel2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, max_length=512, upload_to='media/upload/packaginglevel1/2021/12', verbose_name='Image')),
                ('packaginglevel2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_media', to='quote.packaginglevel2', verbose_name='PackagingLevel2')),
            ],
            options={
                'verbose_name': 'Hình ảnh Bao bì cấp 2',
                'verbose_name_plural': 'Hình ảnh Bao bì cấp 2',
                'ordering': ['id'],
            },
        ),
    ]
