# Generated by Django 3.2.8 on 2021-12-22 08:34

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0016_auto_20211222_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='des',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Mô tả'),
        ),
    ]
