# Generated by Django 3.2.8 on 2021-12-22 08:40

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0017_alter_product_des'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='des',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Mô tả'),
        ),
    ]
