# Generated by Django 3.2.8 on 2022-01-14 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0017_auto_20220114_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='quantity_100_500kg',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Số lượng 100 - 500kg'),
        ),
        migrations.AddField(
            model_name='material',
            name='quantity_less_100kg',
            field=models.CharField(blank=True, max_length=255, verbose_name='Số lượng dưới 100kg'),
        ),
        migrations.AddField(
            model_name='material',
            name='quantity_other',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Số lượng khác'),
        ),
    ]
