# Generated by Django 3.2.8 on 2021-12-24 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0020_bannerhome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerhome',
            name='image',
            field=models.ImageField(blank=True, max_length=512, upload_to='media/upload/bannerhome/2021/12', verbose_name='Image'),
        ),
    ]
