# Generated by Django 3.2.8 on 2021-12-27 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0022_auto_20211225_1335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feeshipping',
            name='product',
        ),
        migrations.RemoveField(
            model_name='feeshipping',
            name='volume',
        ),
    ]
