# Generated by Django 3.2.8 on 2021-12-27 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0023_auto_20211227_0830'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='for_create_quote',
            field=models.BooleanField(blank=True, default=False, verbose_name='Dành cho tạo bảng giá'),
        ),
    ]
