# Generated by Django 3.2.8 on 2021-12-27 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0024_material_for_create_quote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packaginglevel1',
            name='product',
        ),
        migrations.AddField(
            model_name='packaginglevel1',
            name='product',
            field=models.ManyToManyField(blank=True, to='quote.Product', verbose_name='Sản phẩm'),
        ),
    ]
