# Generated by Django 3.2.8 on 2021-12-27 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0025_auto_20211227_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='volume',
            name='number_volume',
            field=models.IntegerField(default=0, verbose_name='Dung tích'),
        ),
        migrations.AlterField(
            model_name='volume',
            name='name',
            field=models.CharField(default='', max_length=20, verbose_name='Tên dung tích'),
        ),
    ]
