# Generated by Django 3.2.8 on 2021-12-27 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0026_auto_20211227_1047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='volume',
        ),
        migrations.RemoveField(
            model_name='packaginglevel2',
            name='product',
        ),
        migrations.AddField(
            model_name='packaginglevel2',
            name='product',
            field=models.ManyToManyField(blank=True, to='quote.Product', verbose_name='Sản phẩm'),
        ),
    ]
