# Generated by Django 3.2.8 on 2021-12-27 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0027_auto_20211227_1716'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=512, upload_to='media/upload/logo/2021/12', verbose_name='Logo')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
            ],
            options={
                'verbose_name': 'Logo',
                'verbose_name_plural': 'Logo',
                'ordering': ['id'],
            },
        ),
    ]
